/**
 * Static SuperMerch menu fallback.
 * Used when the menugroups collection is empty (no dynamic menus created yet).
 * Matches the menuData shape from MenuContext (menugroupName, menus[], id, etc.)
 *
 * To switch to dynamic menus: create MenuGroups and Menus through the admin UI,
 * and this fallback will be automatically bypassed.
 */
const SM_STATIC_MENUS = [
    {
        id: "sm-dashboard",
        menugroupName: "Dashboard",
        sequence: 1,
        isLink: true,
        isActive: true,
        url: "/dashboard",
        menus: [],
    },
    {
        id: "sm-orders",
        menugroupName: "Orders & Customers",
        sequence: 2,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-orders-list", menuName: "Orders", url: "/orders", isActive: true, sequence: 1 },
            { id: "sm-website-users", menuName: "Website Users", url: "/website-users", isActive: true, sequence: 2 },
            { id: "sm-support-tickets", menuName: "Support Tickets", url: "/support-tickets", isActive: true, sequence: 3 },
        ],
    },
    {
        id: "sm-pricing",
        menugroupName: "Pricing & Margins",
        sequence: 3,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-global-margin", menuName: "Global Margin", url: "/pricing/global-margin", isActive: true, sequence: 1 },
            { id: "sm-supplier-margin", menuName: "Supplier Margin", url: "/pricing/supplier-margin", isActive: true, sequence: 2 },
            { id: "sm-category-margin", menuName: "Category Margin", url: "/pricing/category-margin", isActive: true, sequence: 3 },
            { id: "sm-product-margin", menuName: "Product Margin", url: "/pricing/product-margin", isActive: true, sequence: 4 },
            { id: "sm-global-discount", menuName: "Global Discount", url: "/pricing/global-discount", isActive: true, sequence: 5 },
            { id: "sm-supplier-discount", menuName: "Supplier Discount", url: "/pricing/supplier-discount", isActive: true, sequence: 6 },
            { id: "sm-product-discount", menuName: "Product Discount", url: "/pricing/product-discount", isActive: true, sequence: 7 },
        ],
    },
    {
        id: "sm-curation",
        menugroupName: "Curation",
        sequence: 4,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-trending", menuName: "Trending", url: "/curation/trending", isActive: true, sequence: 1 },
            { id: "sm-new-arrivals", menuName: "New Arrivals", url: "/curation/new-arrivals", isActive: true, sequence: 2 },
            { id: "sm-best-sellers", menuName: "Best Sellers", url: "/curation/best-sellers", isActive: true, sequence: 3 },
            { id: "sm-24hour", menuName: "24hr Production", url: "/curation/24hour-production", isActive: true, sequence: 4 },
            { id: "sm-australia", menuName: "Australia Made", url: "/curation/australia-made", isActive: true, sequence: 5 },
            { id: "sm-category-order", menuName: "Category Order", url: "/curation/category-order", isActive: true, sequence: 6 },
            { id: "sm-supplier-priority", menuName: "Supplier Priority", url: "/curation/supplier-priority", isActive: true, sequence: 7 },
        ],
    },
    {
        id: "sm-quotation",
        menugroupName: "Quotation",
        sequence: 5,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-user-quotes", menuName: "User Requests", url: "/quotation/user-requests", isActive: true, sequence: 1 },
            { id: "sm-admin-quotes", menuName: "Admin Quotes", url: "/quotation/admin-quotes", isActive: true, sequence: 2 },
        ],
    },
    {
        id: "sm-products",
        menugroupName: "Products",
        sequence: 6,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-product-master", menuName: "Product Master", url: "/product-master", isActive: true, sequence: 1 },
            { id: "sm-customization-method", menuName: "Customization Method", url: "/customization-method", isActive: true, sequence: 2 },
            { id: "sm-customization-position", menuName: "Customization Position", url: "/customization-position", isActive: true, sequence: 3 },
            { id: "sm-custom-products", menuName: "Custom Products", url: "/custom-products", isActive: true, sequence: 4 },
            { id: "sm-custom-names", menuName: "Custom Names", url: "/custom-names", isActive: true, sequence: 5 },
            { id: "sm-deals", menuName: "Deals", url: "/deals", isActive: true, sequence: 6 },
            { id: "sm-coupon-master", menuName: "Coupons", url: "/coupon-master", isActive: true, sequence: 7 },
            { id: "sm-coupon-banners", menuName: "Coupon Banners", url: "/coupon-banners", isActive: true, sequence: 8 },
        ],
    },
    {
        id: "sm-masters",
        menugroupName: "Masters",
        sequence: 7,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-brand", menuName: "Brand", url: "/brand-master", isActive: true, sequence: 1 },
            { id: "sm-gender", menuName: "Gender", url: "/gender-master", isActive: true, sequence: 2 },
            { id: "sm-main-category", menuName: "Main Category", url: "/main-category", isActive: true, sequence: 3 },
            { id: "sm-sub-category", menuName: "Sub Category", url: "/sub-category", isActive: true, sequence: 4 },
            { id: "sm-collection", menuName: "Collection", url: "/collection", isActive: true, sequence: 5 },
            { id: "sm-color", menuName: "Color", url: "/color", isActive: true, sequence: 6 },
            { id: "sm-material", menuName: "Material", url: "/material", isActive: true, sequence: 7 },
            { id: "sm-size-category", menuName: "Size Category", url: "/size-category", isActive: true, sequence: 8 },
            { id: "sm-size", menuName: "Size", url: "/size", isActive: true, sequence: 9 },
            { id: "sm-supplier", menuName: "Supplier", url: "/supplier-master", isActive: true, sequence: 10 },
            { id: "sm-delivery-type", menuName: "Delivery Type", url: "/delivery-type", isActive: true, sequence: 11 },
            { id: "sm-logistic", menuName: "Logistic Master", url: "/logistic-master", isActive: true, sequence: 12 },
            { id: "sm-currency", menuName: "Currency", url: "/currency-master", isActive: true, sequence: 13 },
            { id: "sm-vat", menuName: "VAT", url: "/vat", isActive: true, sequence: 14 },
            { id: "sm-bank-holiday", menuName: "Bank Holidays", url: "/bank-holidays", isActive: true, sequence: 15 },
        ],
    },
    {
        id: "sm-location",
        menugroupName: "Location",
        sequence: 8,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-country", menuName: "Country", url: "/country", isActive: true, sequence: 1 },
            { id: "sm-state", menuName: "State", url: "/state", isActive: true, sequence: 2 },
            { id: "sm-city", menuName: "City", url: "/city", isActive: true, sequence: 3 },
        ],
    },
    {
        id: "sm-cms",
        menugroupName: "CMS",
        sequence: 9,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-home-banner", menuName: "Home Page Banner", url: "/home-page-banner", isActive: true, sequence: 1 },
            { id: "sm-about-banner", menuName: "About Us Banner", url: "/about-us-banner", isActive: true, sequence: 2 },
            { id: "sm-general-cms", menuName: "General CMS", url: "/general-cms", isActive: true, sequence: 3 },
            { id: "sm-cms-pages", menuName: "CMS Pages", url: "/cms-pages", isActive: true, sequence: 4 },
            { id: "sm-blog", menuName: "Blog", url: "/blog", isActive: true, sequence: 5 },
            { id: "sm-inquiries", menuName: "Inquiries", url: "/inquiries", isActive: true, sequence: 6 },
        ],
    },
    {
        id: "sm-email",
        menugroupName: "Email & Notifications",
        sequence: 10,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-email-setup", menuName: "Email Setup", url: "/email-setup", isActive: true, sequence: 1 },
            { id: "sm-email-for", menuName: "Email For", url: "/email-for", isActive: true, sequence: 2 },
            { id: "sm-email-template", menuName: "Email Template", url: "/email-template", isActive: true, sequence: 3 },
            { id: "sm-email-subs", menuName: "Email Subscriptions", url: "/email-subscriptions", isActive: true, sequence: 4 },
        ],
    },
    {
        id: "sm-settings",
        menugroupName: "Settings",
        sequence: 11,
        isLink: false,
        isActive: true,
        menus: [
            { id: "sm-company", menuName: "Company Details", url: "/company-details", isActive: true, sequence: 1 },
            { id: "sm-shipping", menuName: "Shipping Config", url: "/shipping-config", isActive: true, sequence: 2 },
            { id: "sm-gst", menuName: "GST Config", url: "/gst-config", isActive: true, sequence: 3 },
            { id: "sm-department", menuName: "Department", url: "/department", isActive: true, sequence: 4 },
            { id: "sm-employee", menuName: "Employee", url: "/employee", isActive: true, sequence: 5 },
            { id: "sm-employee-roles", menuName: "Employee Roles", url: "/employee-roles", isActive: true, sequence: 6 },
            { id: "sm-role-master", menuName: "Role Master", url: "/role-master", isActive: true, sequence: 7 },
            { id: "sm-menu-group", menuName: "Menu Group", url: "/menu-group", isActive: true, sequence: 8 },
            { id: "sm-menu-master", menuName: "Menu Master", url: "/menu-master", isActive: true, sequence: 9 },
        ],
    },
];

export default SM_STATIC_MENUS;
